/**
 * OBSOLETE — Do not edit this file.
 *
 * This is leftover scaffolding from the original homebridge-plugin-template.
 * The actual Homebridge plugin lives in packages/homebridge-plugin/src/.
 *
 * This root src/ directory is not referenced by any build script or package.json
 * `main` field. It is kept only to avoid breaking any tooling that may have
 * indexed it, but changes here have NO effect on the running plugin.
 */

import { API } from 'homebridge';

import { PLATFORM_NAME } from './settings.js';
import { EvSolarChargerPlatform } from './platform.js';

/**
 * This method registers the platform with Homebridge.
 * The name provided here must match the `pluginAlias` in config.schema.json.
 */
export default (api: API) => {
  api.registerPlatform(PLATFORM_NAME, EvSolarChargerPlatform);
};
