/**
 * OBSOLETE — Do not edit this file.
 *
 * This is leftover scaffolding from the original homebridge-plugin-template.
 * The actual constants live in packages/homebridge-plugin/src/settings.ts.
 * This file is not compiled or referenced in production.
 */

/**
 * This is the name of the platform that users will use to register the plugin in the Homebridge config.json
 */
export const PLATFORM_NAME = 'EvSolarCharger';

/**
 * This must match the name of your plugin as defined the package.json `name` property
 */
export const PLUGIN_NAME = 'homebridge-ev-solar-charger';
